Fix implicit declaration of 'FIPS_mode' function
With '--enable-fips-mode' the 'FIPS_mode' function gets exposed and
its <openssl/crypto.h> header file needs to be included:

    server.c: In function ‘view_loaded’:
    server.c:9677:10: error: implicit declaration of function ‘FIPS_mode’ [-Werror=implicit-function-declaration]
              FIPS_mode() ? "enabled" : "disabled");
              ^~~~~~~~~